a = input('Digite algo?')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaço? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabertico: ', a.isalpha())
print('É alfalnumérico? ', a.isalnum())
print('Esta em maiúscula? ', a.isupper())
print('Esta em minúscula? ', a.islower())
print('Esta capitalizada? ', a.istitle())